kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: devboard-ns

spec:
  clusterIP: None    # It will make this Service Headless. It won't have any IP
  selector:
    app: devboard-postgres

  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
